### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [giantswarm/kubectl-gs#1050]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by Strigix** [comment]
Hey @igibek ! 

I'm doing well, thank you, what about yourself? 

First of all, thank you for reaching out! The effort is already appreciated.
I'll talk with the team about enabling this feature, thanks for letting me know.

In the meanwhile, would you please be so kind to check the following page for us? 🙏🏻 

https://www.giantswarm.io/responsible-disclosure

That way you can already report the issue without having to wait for the feature!
