### ISSUE TITLE
Multiarch Docker image

### ISSUE THREAD

**Issue by theBNT** [giantswarm/kubectl-gs#1419]
hi,

is it possible to create a multi-arch docker image by e.g. using buildx at

https://github.com/giantswarm/kubectl-gs/blob/54b3ce6a36056d7a71f669dbdd8127b4cdaeddb3/Makefile.gen.go.mk#L162

Maybe its sufficient to build via:
```
docker buildx build --platform=linux/amd64 -t ${APPLICATION}:${VERSION} .
```

Im using this image as a base-image for https://github.com/giantswarm/devctl/issues/1047 and i get the warning on a windows system using docker desktop:

```
1 warning found:
 - InvalidBaseImagePlatform: Base image quay.io/giantswarm/kubectl-gs was pulled with platform "linux/386", expected "linux/amd64" for current build (line 1)
Base image platform does not match expected target platform
```

Probably `linux/386` is some default but outdated anyway?

Looking at quay i could not find information regarding arch:

https://quay.io/repository/giantswarm/kubectl-gs/manifest/sha256:02c628b7245ec7cdd4e3618a7112026720a2c25f2e5f4c7371cced3c17953636

It also doesnt help to use `--platform=${BUILDPLATFORM}` in the Dockerfile or `--platform=linux/amd64` in the commandline.

**Comment by ljakimczuk** [comment]
Hey @theBNT, it seems the `linux/386` is your platform, for as far as I can tell, the `kubectl-gs` has already been built for the `linux/amd64`, you can check that by inspecting it after pulling like: 

```text
> docker inspect quay.io/giantswarm/kubectl-gs:latest
[
    {
        ...
        "Architecture": "amd64",
        "Os": "linux",
        ...
    }
]
```

I'm checking the possibility to leverage the multi-arch build to provide the `linux/386`.

**Comment by ljakimczuk** [comment]
@theBNT I updated the pipelines to build both, the`linux/amd64` and the `linux/386` images, both going to be available from the next release onward.

**Comment by theBNT** [comment]
just as a quick feedback, build runs without errors now on my end, thanks a lot!
